package com.boot.controller;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.boot.model.Item;
import com.boot.repository.ItemRepository;
import com.boot.service.FilterService;
import com.boot.service.UtilService;

@Controller  
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class APIController {
	
	@Autowired  // Get the bean called itemRepository, which is auto-generated by Spring. We will use it to handle the data
	private ItemRepository itemRepository;

	@Autowired
    private FilterService filterService;
	
	@RequestMapping(path="/all", method=RequestMethod.GET)
	public @ResponseBody Iterable<Item> getAllUsers() {
		// This returns a JSON or XML with the users
		return itemRepository.findAll();
	}
	
	
	@RequestMapping(path="/criteria", method=RequestMethod.GET)
	public @ResponseBody Iterable<Item> getByCriteria (
			@RequestParam(required = false) Long id,
			@RequestParam(required = false) String description,	
			@RequestParam(required = false) String lastSold,	
			@RequestParam(required = false) Integer shelfLife,				
			@RequestParam(required = false) String department,	
			@RequestParam(required = false) Double price,				
			@RequestParam(required = false) Double cost) {

		
		return filterService.getResults(id, description, lastSold, shelfLife, department, price, cost);
	}	
}